"""Add UserProfile with one-to-one relationship

Revision ID: 45e8a8c81998
Revises: 198bfffbd783
Create Date: 2026-05-22 17:59:50.221794

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "45e8a8c81998"
down_revision: Union[str, Sequence[str], None] = "198bfffbd783"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "userprofile",
        sa.Column("bio", sa.String(length=256), nullable=False),
        sa.Column("avatar_url", sa.String(length=256), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_userprofile_id"), "userprofile", ["id"], unique=False)
    op.create_index(op.f("ix_userprofile_user_id"), "userprofile", ["user_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_userprofile_user_id"), table_name="userprofile")
    op.drop_index(op.f("ix_userprofile_id"), table_name="userprofile")
    op.drop_table("userprofile")
    # ### end Alembic commands ###
