"""Add password hash field

Revision ID: 65f5a3f519b1
Revises: 45e8a8c81998
Create Date: 2026-05-25 17:37:53.210303

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "65f5a3f519b1"
down_revision: Union[str, Sequence[str], None] = "45e8a8c81998"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("_password_hash", sa.String(length=128), nullable=False))
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_index(op.f("ix_user_username"), table_name="user")
    op.drop_column("user", "email")
    op.drop_column("user", "username")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("username", sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column("user", sa.Column("email", sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.create_index(op.f("ix_user_username"), "user", ["username"], unique=True)
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.drop_column("user", "_password_hash")
    # ### end Alembic commands ###
