"""Add score column to User

Revision ID: ca348691a7da
Revises: ef214891a500
Create Date: 2026-06-09 20:34:39.265882

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ca348691a7da"
down_revision: Union[str, Sequence[str], None] = "ef214891a500"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("score", sa.Integer(), nullable=True))
    op.execute('UPDATE "user" SET score = 0 WHERE score IS NULL')
    op.alter_column("user", "score", nullable=False)
    op.drop_index(op.f("ix_userprofile_bio_english_fts"), table_name="userprofile", postgresql_using="gin")
    op.create_index(
        "ix_userprofile_bio_english_fts",
        "userprofile",
        [sa.literal_column("to_tsvector(CAST('english' AS REGCONFIG), bio)")],
        unique=False,
        postgresql_using="gin",
    )
    op.drop_index(op.f("ix_userprofile_bio_russian_fts"), table_name="userprofile", postgresql_using="gin")
    op.create_index(
        "ix_userprofile_bio_russian_fts",
        "userprofile",
        [sa.literal_column("to_tsvector(CAST('russian' AS REGCONFIG), bio)")],
        unique=False,
        postgresql_using="gin",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_userprofile_bio_russian_fts", table_name="userprofile", postgresql_using="gin")
    op.create_index(
        op.f("ix_userprofile_bio_russian_fts"),
        "userprofile",
        [sa.literal_column("to_tsvector('russian'::regconfig, bio)")],
        unique=False,
        postgresql_using="gin",
    )
    op.drop_index("ix_userprofile_bio_english_fts", table_name="userprofile", postgresql_using="gin")
    op.create_index(
        op.f("ix_userprofile_bio_english_fts"),
        "userprofile",
        [sa.literal_column("to_tsvector('english'::regconfig, bio)")],
        unique=False,
        postgresql_using="gin",
    )
    op.drop_column("user", "score")
    # ### end Alembic commands ###
