apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      serviceAccountName: default
      automountServiceAccountToken: true
      volumes:
        - name: vault-storage
          persistentVolumeClaim:
            claimName: vault-storage
      containers:
        - name: vault
          image: hashicorp/vault:2.0.1
          securityContext:
            capabilities:
              add:
                - IPC_LOCK
          command:
            - "/bin/sh"
            - "-c"
            - |
              cat > /tmp/vault.hcl <<EOF
              storage "file" {
                path = "/vault/data"
              }
              listener "tcp" {
                address = "0.0.0.0:8200"
                tls_disable = true
              }
              disable_mlock = true
              api_addr = "http://vault.app.svc:8200"
              cluster_addr = "https://vault.app.svc:8201"
              EOF
              exec vault server -config=/tmp/vault.hcl
          ports:
            - containerPort: 8200
              name: http
          volumeMounts:
            - name: vault-storage
              mountPath: /vault/data
          readinessProbe:
            httpGet:
              path: /v1/sys/health
              port: 8200
            initialDelaySeconds: 5
            periodSeconds: 3
          startupProbe:
            httpGet:
              path: /v1/sys/health
              port: 8200
            failureThreshold: 60
            periodSeconds: 5
